name: project_env_yml
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_5
  - ca-certificates=2023.12.12=hca03da5_0
  - libffi=3.4.4=hca03da5_0
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.13=h1a28f6b_0
  - pip=23.3.1=py311hca03da5_0
  - python=3.11.8=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.2.2=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - wheel=0.41.2=py311hca03da5_0
  - xz=5.4.6=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - aiohappyeyeballs==2.3.7
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==24.2.0
      - audioread==3.0.1
      - backports-tarfile==1.2.0
      - black==24.10.0
      - certifi==2024.8.30
      - cffi==1.17.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.21.0
      - decorator==5.1.1
      - dill==0.3.8
      - distlib==0.3.9
      - docutils==0.21.2
      - filelock==3.16.1
      - flake8==7.1.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - huggingface-hub==0.24.5
      - hydra-core==1.3.2
      - identify==2.6.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jedi==0.19.1
      - joblib==1.4.2
      - keyring==25.4.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nh3==0.2.18
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==2.1.2
      - omegaconf==2.3.0
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pillow==11.0.0
      - pkginfo==1.10.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - pre-commit==4.0.1
      - pudb==2024.1.2
      - pyarrow==17.0.0
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydevtips==0.0.3
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - readme-renderer==44.0
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.9.2
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - six==1.16.0
      - soundfile==0.12.1
      - soxr==0.4.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - twine==5.1.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.3
      - urwid==2.6.15
      - urwid-readline==0.14
      - virtualenv==20.27.0
      - wcwidth==0.2.13
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==3.20.2
prefix: /Users/eric/anaconda3/envs/project_env
